theme: jekyll-theme-architect

title: "Clases de Implantación de Sistemas Operativos"

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "."
      type: posts
    values:
      layout: post
      comments: true
      share: true
